apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-kv
  namespace: haruka
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "928bd575-883e-4b6b-aefa-2759dff17a96"
    keyvaultName: "kv-haruka"
    tenantId: "404cf0ed-d7da-4251-b055-5d91f751ff85"
    objects: |
      array:
        - |
          objectName: GITHUB-TOKEN
          objectType: secret
          objectAlias: github-token
        - |
          objectName: SMTP-USER
          objectType: secret
          objectAlias: smtp-user
        - |
          objectName: SMTP-PASSWORD
          objectType: secret
          objectAlias: smtp-password
        - |
          objectName: SMTP-HOST
          objectType: secret
          objectAlias: smtp-host
        - |
          objectName: SMTP-PORT
          objectType: secret
          objectAlias: smtp-host
        - |
          objectName: CONTACT-RECIPIENT
          objectType: secret
          objectAlias: contact-recipient
        - |
          objectName: ALLOWED-ORIGINS
          objectType: secret
          objectAlias: allowed-origins

